# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20170724_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='cliente',
            new_name='venta',
        ),
    ]
